### ISSUE TITLE
Can't use /invest companies

### ISSUE THREAD

**Issue by capuano1** [Hugo1307/BlockStreet#1]
I already have not only op but all the permissions on BlockStreet and on the server (* permission) but it says that I don't have enough permissions to use the command /invest companies to see the list of available companies. I'm using Spigot 1.15.2-R0.1
EDIT: The only commands that don't give me that error is /invest (to see all commands) and /invest create. All of the other commands (companies, company, buy, sell and actions) give me that error

**Comment by Hugo1307** [comment]
Hi,
I analyzed the plugin and indeed you're right. The problem was solved in the most recent release.

Thank you for using my plugin!

Best regards,
Hugo1307
