### ISSUE TITLE
Issue Crating Company + Further help

### ISSUE THREAD

**Issue by INSCCOIN** [Hugo1307/BlockStreet#10]
So i might not understand by what "predefined actions" mean but i cant seem to create a company. What sould the sring look like if you could give me an example of it. Thanks!

**Comment by Hugo1307** [comment]
The "predefined actions" refer to the number of shares that you want players to be able to purchase. For instance, if you set the "availableActions" parameter to 1000, players will be able to buy a maximum of 1000 shares in your company.

To create a new company named "MyCompany" with 1000 shares and an initial price p/ share of 100$, you can do:
`/invest create MyCompany 4 1000 100.0`

**Comment by Hugo1307** [comment]
I'll close this issue due to inactivity. Please feel free to re-open it or open a new one if you need extra help.
