### ISSUE TITLE
Price of the actions don't change

### ISSUE THREAD

**Issue by capuano1** [Hugo1307/BlockStreet#3]
So, basically I bought some some actions from Blocks Companion and waited for the actions to be updated. After it updated, my /invest actions value was lower (sad, but it happens), but the price to buy new actions still remained the same as it was before, and I think that number also needed to change, in the same rate that my actions value changed.
Oh, and a suggestion: Maybe add dividends? Saw that option on a old and outdated Stock Market plugin, and I guess that would be nice to have maybe? Maybe even have a option to disable, in case the server owners don`t want that kind of stuff.

**Comment by Hugo1307** [comment]
Problem solved in the most recent release.

Thank you for using my plugin

Best regards,
Hugo1307
