### ISSUE TITLE
Minor thing

### ISSUE THREAD

**Issue by capuano1** [Hugo1307/BlockStreet#5]
Sorry to bother you again, but I found a minor thing: if you do /invest actions when you have no actions, it gives the message "This company doesn't have have enough actions to sell.", instead of showing something like "You don't have any actions.". This is a minor thing, so no need to solve it as fast as possible, since it doesn't really changes the way the plugin works.

**Comment by Hugo1307** [comment]
Problem solved in the most recent release. 
If you have any other problem don't hesitate to contact me.

Thank you for using my plugin!

Best regards,
Hugo1307
