### ISSUE TITLE
Created companies dont change in value

### ISSUE THREAD

**Issue by blockoboyo** [Hugo1307/BlockStreet#7]
I have used /invest create to create many companies, however when the values change it only affects the default 3, the others don't change in value.

**Comment by Hugo1307** [comment]
Hey. Do you have any error in your server console?

**Comment by blockoboyo** [comment]
No warnings or errors occur in console, the companies are listen in /invest
companies and players can buy stocks of them. The only issue is that the
values never change

**Comment by Hugo1307** [comment]
Okay. Thanks for your report. 
I'll look into it and let you know when I have a solution.

**Comment by blockoboyo** [comment]
Sounds good, thanks!
